### ISSUE TITLE
Needs a "source" format that can convert losslessly to .pie

### ISSUE THREAD

**Issue by dak180** [Warzone2100/WMIT#1]
Since [warzone2100](https://github.com/Warzone2100/warzone2100) (and all its art) is under GPLv2 we need a format that qualifies as a "preferred editing format".

Current candidates include [.obj](http://en.wikipedia.org/wiki/.obj) and [.dae](http://en.wikipedia.org/wiki/COLLADA).

In addition to the mesh this format needs to be able to handle all the other things that .pie supports like: connectors, the animation system, special flags and team colours.

These needs might be met with a separate file or by adding the data in some way to the export format; care should be taken to make editing easy and unlikely to result in unintentional loss of data when edited in other programs.

**Comment by bjorn-ali-goransson** [comment]
Closing this IMO, this one's waited long enough
