### ISSUE TITLE
Inverted normals

### ISSUE THREAD

**Issue by MaNGusT-** [Warzone2100/WMIT#22]
[pieNormals_test6.zip](https://github.com/Warzone2100/WMIT/files/6176481/pieNormals_test6.zip)

_Testing_: to exclude effect of broken shaders, you need to NOT specify a normal map for a testing model.

1) *BUG* If open a model without vertex normals (pie2 or pie3) and don't use normal map, WMIT calculates and shows face normals as inverted.
![1](https://user-images.githubusercontent.com/1297887/111581951-30193000-87cb-11eb-9b64-ad561d15aa86.jpg)

2) *BUG* If open a model with  vertex normals(OBJ) and don't use normal map, WMIT inverts normals and shows them inverted.
![2](https://user-images.githubusercontent.com/1297887/111582218-956d2100-87cb-11eb-973b-a92312de451b.jpg)

3) *BUG* If open an OBJ model with vertex normals and then save it to PIE3 with vertex normals, then WMIT saves inverted normals.
![3](https://user-images.githubusercontent.com/1297887/111583208-1bd63280-87cd-11eb-90c4-aed5eef1f54a.jpg)

4) *NOT A BUG* If open PIE3 with inverted normals that were previously saved, then WMIT still shows them inverted.

P.S. When it will be fixed, I will need to fix shaders and re-export models that use vertex normals in ARmod.

**Comment by inodlite** [comment]
Should be fine after #28...
