### ISSUE TITLE
Requirements missed for installing on Ubuntu.

### ISSUE THREAD

**Issue by Cjkjvfnby** [Warzone2100/WMIT#3]
I try to install.sh on my Ubuntu 12.04 and fail

There is no requirements specified in project.
1. cmake
2. some QT 

-- Could NOT find QGLViewer headers.
-- Could NOT find QGLViewer library.
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find Qt4 (missing: QT_QMAKE_EXECUTABLE QT_MOC_EXECUTABLE
  QT_RCC_EXECUTABLE QT_UIC_EXECUTABLE QT_INCLUDE_DIR QT_LIBRARY_DIR
  QT_QTCORE_LIBRARY)
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindQt4.cmake:1171 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:11 (find_package)

**Comment by past-due** [comment]
I realize this is an ancient issue, but this should now (finally) be fixed with the latest commits, and: https://github.com/Warzone2100/WMIT/blob/master/README.md
